### ISSUE TITLE
Announce COWG as a community group

### ISSUE THREAD

**Issue by cassandraoid** [golang/cowg#12]
To make this feel like a community initiative I recommend we announce it to the community on the Golang blog or on the future Go Community medium account or both.

- [x]  Write up charter
- [x]  Define membership
- [x]  Publish on the golang.org blog

**Comment by spf13** [comment]
We should announce it on the golang.org blog.

**Comment by spf13** [comment]
- [ ]  Write up charter
- [ ]  Define membership
- [ ]  Publish on the golang.org blog

**Comment by dlsniper** [comment]
Hi,

I've been looking for a place to ask these questions so I guess this is just as good as it could be:
- what's the purpose of this "group"?
- why is this open but nobody knows about it, no announcement, no nothing on the known comms channels (golang-nuts, Gophers Slack, /r/golang etc)
- why aren't the discussions done in public if the group is public?
- how can I join to this group (once I figure out what it does and why it exists)?
- how is this different from the devexp initiative?

Thank you.

**Comment by carlisia** [comment]
I would love to have @cassandraoid on the @gotimefm podcast to talk exactly about the questions @dlsniper is asking.  What say you Cassandra?

**Comment by spf13** [comment]
We will announce it shortly. After the announcement it would be great to get extra exposure for the working group and nobody is better than @cassandraoid to interview.

**Comment by ymotongpoo** [comment]
@cassandraoid @spf13 I think the task of this ticket is done by publishing [this article](https://blog.golang.org/developer-experience). No?

**Comment by spf13** [comment]
No. That's for a different working group. This working group has a separate
post.

https://go-review.googlesource.com/c/blog/+/60774

**Comment by spf13** [comment]
The blog post is now live
https://blog.golang.org/community-outreach-working-group
