### ISSUE TITLE
Create a Meetup Organizers Registration form

### ISSUE THREAD

**Issue by cassandraoid** [golang/cowg#4]
- [x] create form in doc
- [x] translate doc to form
- [x] distribute form via social media + slack

Do we want to create a blog about this?

**Comment by campoy** [comment]
Form created and shared with all the leads so they can edit.

up to you to fill it up, @cassandraoid.

Thanks!

**Comment by cassandraoid** [comment]
Waiting for a review then will post to social.

**Comment by cassandraoid** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeBt4A1FKmryN5gOLITEgrcIPHsifV4pR9EmZoL1dvaK1vTjA/viewform#responses
